### ISSUE TITLE
Password encryption

### ISSUE THREAD

**Issue by Smedzlatko** [gigsterous/api#22]
Passwords should not be stored as plain text in the database. Find a way how to encrypt them or store only their hash in the authorisation server.

**Comment by svachmic** [comment]
I'd go with [BCrypt](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/crypto/bcrypt/BCrypt.html) for [obvious reasons](http://security.stackexchange.com/questions/4781/do-any-security-experts-recommend-bcrypt-for-password-storage). 🔒
